In [1]:
import pandas as pd

In [2]:
data= pd.read_csv ("../results/cleaned_titles.csv")

In [3]:
data.shape

(199293, 5)

In [11]:
data.head()

,user-id,game-title,behavior,value,canonical_title
0,151603712,The Elder Scrolls V Skyrim,purchase,1.0,The Elder Scrolls V Skyrim
1,151603712,The Elder Scrolls V Skyrim,play,273.0,The Elder Scrolls V Skyrim
2,151603712,Fallout 4,purchase,1.0,Fallout 4
3,151603712,Fallout 4,play,87.0,Fallout 4
4,151603712,Spore,purchase,1.0,Spore

In [12]:
data.tail()

,user-id,game-title,behavior,value,canonical_title
199288,128470551,Titan Souls,play,1.5,Titan Souls
199289,128470551,Grand Theft Auto Vice City,purchase,1.0,Grand Theft Auto
199290,128470551,Grand Theft Auto Vice City,play,1.5,Grand Theft Auto
199291,128470551,RUSH,purchase,1.0,RUSH
199292,128470551,RUSH,play,1.4,RUSH

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 199293 entries, 0 to 199292
Data columns (total 5 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   user-id          199293 non-null  int64
 1   game-title       199293 non-null  object
 2   behavior         199293 non-null  object
 3   value            199293 non-null  float64
 4   canonical_title  199293 non-null  object
dtypes: float64(1), int64(1), object(3)
memory usage: 7.6+ MB

In [14]:
print (data.isnull().sum())

user-id            0
game-title         0
behavior           0
value              0
canonical_title    0
dtype: int64